Added focus nodes
CircuitVerse/mobile-app pull request #34
Opened 2020-11-30 08:21 UTC by jaggu21

Covers #31

2020-11-30 18:43 UTC, Nitish145 requested changes

2020-11-30 18:43 UTC, Nitish145 commented on lib/ui/components/cv_password_field.dart
> +    this.focus_node,
follow `camelCase` convention here.

2020-11-30 18:43 UTC, Nitish145 commented on lib/ui/components/cv_password_field.dart
> +        focusNode: widget.focus_node,
It's better to keep focusNode as the first parameter because it kind of defines the text field

2020-11-30 18:43 UTC, Nitish145 commented on lib/ui/components/cv_text_field.dart
> +  final FocusNode focus_node;
camelCase

2020-11-30 18:43 UTC, Nitish145 commented on lib/ui/components/cv_text_field.dart
> +  final Function(String) fieldSubmitted;
Follow the naming conventions for functional callbacks, `fieldSubmitted` -> `onFieldSubmitted`.

2020-11-30 18:43 UTC, Nitish145 commented on lib/ui/views/authentication/login_view.dart
> +  final _focusNode = FocusNode();
FocusNode's name should be indicative of the text field it'll be a property of.

2020-11-30 18:43 UTC, Nitish145 commented on lib/ui/views/authentication/login_view.dart
> +      fieldSubmitted: (_) {
Use arrow functions for single line callbacks.

2020-11-30 18:43 UTC, Nitish145 commented on lib/ui/views/authentication/login_view.dart
> +      focus_node: _focusNode,
Again, the focus node is better to be the first argument of the text field.

2020-11-30 18:43 UTC, Nitish145 commented on lib/ui/views/authentication/signup_view.dart
> +  final _focusNode1 = FocusNode();
Focus Node nomenclature, refer above comments.

2020-12-01 08:45 UTC, Nitish145 approved these changes

2020-12-03 03:09 UTC, Nitish145 commented
@jaggu21 we need to add this stuff for other forms too. Please add those in separate PRs.

2020-12-03 03:09 UTC, merged

2020-12-03 04:43 UTC, jaggu21 commented
@Nitish145 Sure ,I will do that as soon as possible !