feat: Removed the description section when there is not description
CircuitVerse/mobile-app pull request #49
Opened 2021-01-09 08:33 UTC by pratikbaid3

Fixes #

Describe the changes you have made in this PR -
The description field now only shows up is the description field has some data. Earlier it was showing "Description: " even though the circuit did not have any.

Screenshots of the changes (If any) -
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-09 at 14 01 11](https://user-images.githubusercontent.com/52864956/104087077-2a5f1580-5283-11eb-9bb7-f792e8e55c44.png)

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

2021-01-09 09:33 UTC, manjotsidhu approved these changes

2021-01-09 11:48 UTC, Nitish145 commented on lib/ui/views/projects/project_details_view.dart
> +        padding: const EdgeInsets.symmetric(vertical: 4.0),
Unnecessary padding without any text can be removed. Better to just return a `Container` when the condition is fulfilled so no unnecessary padding is there.

2021-01-09 12:27 UTC, pratikbaid3 commented
I have made the change @Nitish145

2021-01-13 14:04 UTC, Nitish145 requested changes
@pratikbaid3 remove unnecessary changes, the only relevant file change i see is in `project_details_view.dart`

2021-01-15 05:31 UTC, closed without merging