Skimmer effect while fetching featured circuits
CircuitVerse/mobile-app pull request #57
Opened 2021-01-19 06:46 UTC by iCoder-007

Screenshot :

<img src="https://user-images.githubusercontent.com/55887676/104997474-a2ea7280-59f7-11eb-9ebc-9a0ceef3c5e8.jpg"  width="300px" height="600px">

2021-01-19 15:04 UTC, manjotsidhu requested changes

2021-01-19 15:04 UTC, manjotsidhu commented on lib/ui/components/cv_skimmer.dart
> +class Shimmer extends StatefulWidget {
Class name and file name should follow the same name.

2021-01-19 15:04 UTC, manjotsidhu commented on lib/ui/components/cv_skimmer.dart
> +import 'package:flutter/material.dart';
Typo "Skimmer" -> "Shimmer"

2021-01-20 13:45 UTC, iCoder-007 commented
Fixed typos please have a look

2021-01-20 16:16 UTC, manjotsidhu requested changes

2021-01-20 16:16 UTC, manjotsidhu commented on lib/ui/views/projects/featured_projects_view.dart
> +          _items.add(Padding(
We can reduce code by making a single widget and adding it to the list 3 times.

2021-01-21 15:01 UTC, manjotsidhu approved these changes
Looks good, can we get this shimmer loading in other views as well where projects are fetched ?

2021-01-22 04:34 UTC, iCoder-007 commented
okk i will do that

2021-01-25 05:05 UTC, iCoder-007 commented
ui test are failing in user_projects_view.dart
what's the issue

logs

00:50 +226 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/profile/profile_view_test.dart: ProfileViewTest - finds Generic MyGroupsView widgets [E]                       
  Test failed. See exception logs above.
  The test description was: finds Generic MyGroupsView widgets
  
00:51 +226 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/authentication/signup_view_test.dart: SignupViewTest - When name/email/password is not valid or empty, proper error message should be shown
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
00:51 +227 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/authentication/forgot_password_view_test.dart: ForgotPasswordViewTest - New User? Sign Up onTap takes to SignupView
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
00:51 +228 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/authentication/forgot_password_view_test.dart: ForgotPasswordViewTest - When email is not valid or empty, proper error message should be shown
[GOING TO ROUTE] /
00:52 +228 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/authentication/login_view_test.dart: LoginViewTest - New User? Sign Up onTap takes to SignupView               
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
00:52 +229 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/authentication/login_view_test.dart: LoginViewTest - When email/password is not valid or empty, proper error message should be shown
[GOING TO ROUTE] /
00:52 +229 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/profile/edit_profile_view_test.dart: EditProfileViewTest - finds Generic MyGroupsView widgets                  
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
00:52 +230 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/profile/edit_profile_view_test.dart: EditProfileViewTest - on Save Details is Tapped                           
[GOING TO ROUTE] /
00:52 +230 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/authentication/forgot_password_view_test.dart: ForgotPasswordViewTest - When email is not valid or empty, proper error message should be shown
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
00:54 +231 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/profile/user_projects_view_test.dart: UserProjectsViewTest - finds Generic MyGroupsView widgets                
[GET] GetMaterialController has been initialized
00:54 +231 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/profile/edit_profile_view_test.dart: EditProfileViewTest - on Save Details is Tapped                           
[BACK ROUTE] /
[OPEN SNACKBAR] snackbar
[CLOSE SNACKBAR] snackbar
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
00:54 +232 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/authentication/login_view_test.dart: LoginViewTest - When email/password is not valid or empty, proper error message should be shown
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
00:54 +233 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/profile/user_projects_view_test.dart: UserProjectsViewTest - finds Generic MyGroupsView widgets                
[GOING TO ROUTE] /
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
00:56 +234 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/profile/user_projects_view_test.dart: UserProjectsViewTest - Project Page is Pushed onTap View button          
[GOING TO ROUTE] /
[GOING TO ROUTE] null
LocalStorageService:_getFromDisk. key: logged_in_user value: null
LocalStorageService:_getFromDisk. key: is_logged_in value: null
LocalStorageService:_getFromDisk. key: is_logged_in value: null
LocalStorageService:_getFromDisk. key: logged_in_user value: null
LocalStorageService:_getFromDisk. key: logged_in_user value: null
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
00:59 +235 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - finds Generic MyGroupsView widgets                         
[GET] GetMaterialController has been initialized
[GOING TO ROUTE] /
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
01:00 +236 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - New Group Page is Pushed onTap                             
[GOING TO ROUTE] /
01:00 +236 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/teachers/teachers_view_test.dart: TeachersViewTest - finds TeachersView Widgets                                
[GET] GetMaterialController has been initialized
01:01 +236 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - New Group Page is Pushed onTap                             
[GOING TO ROUTE] null
01:01 +236 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/teachers/teachers_view_test.dart: TeachersViewTest - finds TeachersView Widgets                                
[GOING TO ROUTE] /
01:02 +236 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - New Group Page is Pushed onTap                             
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
01:02 +237 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - View Group Details Page is Pushed onTap                    
[GOING TO ROUTE] /
01:02 +237 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/startup/startup_view_test.dart: StartupViewTest - finds CircuitVerse logo on StartUpView                       
[GET] GetMaterialController has been initialized
01:03 +237 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - View Group Details Page is Pushed onTap                    
[GOING TO ROUTE] null
01:03 +237 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/teachers/teachers_view_test.dart: TeachersViewTest - finds TeachersView Widgets                                
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
01:03 +238 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/startup/startup_view_test.dart: StartupViewTest - finds CircuitVerse logo on StartUpView                       
[GOING TO ROUTE] /
01:03 +238 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - View Group Details Page is Pushed onTap                    
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
01:03 +239 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - Edit Group View is Pushed onTap                            
[GOING TO ROUTE] /
01:03 +239 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - Edit Group View is Pushed onTap                            
[GOING TO ROUTE] null
01:04 +239 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/groups/my_groups_view_test.dart: MyGroupsViewTest - Edit Group View is Pushed onTap                            
[GET] onClose of GetMaterialController called
[GET] GetMaterialController deleted from memory
01:0 [...]

2021-01-26 05:10 UTC, manjotsidhu commented
In the logs I can see only ProfileViewTest failing and without exception logs. Can you send the full logs ? and also push the changes which are causing this, so that I can check.
```
00:50 +226 -1: /home/saurabh/Desktop/circutverseapp/mobile-app/test/ui_tests/profile/profile_view_test.dart: ProfileViewTest - finds Generic MyGroupsView widgets [E]
Test failed. See exception logs above.
```

2021-01-26 13:01 UTC, Nitish145 commented
What exactly is the utility of using the exact same code from https://pub.dev/packages/shimmer rather than to just increase the number lines? @iCoder-007 

Also, it's better to discuss this in #ux channel because if this gets approved, it should be used in place of all the loading indicators.

2021-01-31 13:02 UTC, manjotsidhu commented
> What exactly is the utility of using the exact same code from https://pub.dev/packages/shimmer rather than to just increase the number lines? @iCoder-007
> 
> Also, it's better to discuss this in #ux channel because if this gets approved, it should be used in place of all the loading indicators.

@iCoder-007

2021-02-05 16:28 UTC, iCoder-007 commented
Where is ux channel

2021-02-05 17:56 UTC, manjotsidhu commented
> Where is ux channel

Check Slack Channel

2021-05-06 11:41 UTC, manjotsidhu commented
> What exactly is the utility of using the exact same code from https://pub.dev/packages/shimmer rather than to just increase the number lines? @iCoder-007
> 
> Also, it's better to discuss this in #ux channel because if this gets approved, it should be used in place of all the loading indicators.

@iCoder-007 can you use `shimmer` package instead of using it locally ? Rest of the things looks good to me.

2021-05-06 17:49 UTC, tachyons commented
Also you can't simply copy paste code from another open source library as it will be a copyright violation. For instance shimmer library is licensed under BSD, so copying code to our code base requires copyright notice from the original code

2021-10-03 15:02 UTC, manjotsidhu commented
Since the PR is now stale and due to new changes, I am closing this PR. Feel free to open another one anytime :)
Thanks for Contributing 👍

2021-10-03 15:02 UTC, closed without merging