Add a text message if no circuits or favourites are present
CircuitVerse/mobile-app pull request #65
Opened 2021-01-30 18:03 UTC by spiderxm

Added text message and button to navigate to Featured Circuits Screen

2021-02-01 05:01 UTC, manjotsidhu commented on lib/ui/views/profile/user_projects_view.dart
> +import '../../components/cv_primary_button.dart';
Package imports.

2021-02-05 18:02 UTC, manjotsidhu approved these changes

2021-05-20 12:15 UTC, Nitish145 requested changes

2021-05-20 12:15 UTC, Nitish145 commented on lib/ui/views/profile/user_favourites_view.dart
> +          return Center(
This widget is used in multiple places, hence code duplication, can you make a component in `lib/ui/components` named maybe `cv_no_items_widget.dart`, and move this logic there. Obviously, we would expect you to make the component dynamic that takes in the `title`, `buttonText`, `onTap` params to build the widget.

Also, it's better to check if `onTap` is `null` then just remove the button.

2021-05-22 10:47 UTC, closed without merging