Icon change successful
CircuitVerse/mobile-app pull request #96
Opened 2021-05-22 08:49 UTC by Anshnrag02

All the fixes regarding the logo have been made. 

![WhatsApp Image 2021-05-22 at 2 17 54 PM](https://user-images.githubusercontent.com/75090766/119220537-a5c1b500-bb08-11eb-9dc2-a8a214dc45f1.jpeg)

Resizing and shape binding has been done!

Kindly merge the PR

2021-05-22 14:25 UTC, manjotsidhu commented
@Nitish145 can you approve workflow run, I would like to test the build.

2021-05-22 14:27 UTC, manjotsidhu requested changes

2021-05-22 14:27 UTC, manjotsidhu commented on pubspec.lock
>        name: async
Exclude changes from this file.

2021-05-22 14:27 UTC, manjotsidhu commented on pubspec.yaml
> +    - android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
Are you sure that these android/* assets are specifically required to be included ? I don't think so

2021-05-22 15:14 UTC, Anshnrag02 commented
Yeah I synced the assets wrongly. Made the changes! sharing them

2021-05-22 15:19 UTC, Anshnrag02 commented
Please check now @manjotsidhu

2021-05-22 15:20 UTC, Anshnrag02 commented
Yeah I corrected them.

On Sat, 22 May 2021 at 19:57, Manjot Singh Sidhu ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In pubspec.lock
> <https://github.com/CircuitVerse/mobile-app/pull/96#discussion_r637410316>
> :
>
> > @@ -28,7 +28,7 @@ packages:
>        name: async
>
> Exclude changes from this file.
> ------------------------------
>
> In pubspec.yaml
> <https://github.com/CircuitVerse/mobile-app/pull/96#discussion_r637410382>
> :
>
> > @@ -78,6 +78,22 @@ flutter:
>      - assets/images/signup/
>      - assets/images/group/
>      - assets/images/profile/
> +    - android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
>
> Are you sure that these android/* assets are specifically required to be
> included ? I don't think so
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CircuitVerse/mobile-app/pull/96#pullrequestreview-666186085>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR44WTSQQJKRNEKAMVVNAITTO65NXANCNFSM45KN2IQQ>
> .
>

2021-05-22 16:41 UTC, manjotsidhu commented
I will get back to soon after I tested this personally.

2021-05-22 16:45 UTC, manjotsidhu reviewed
Looks good, let me test it out.

2021-05-22 17:08 UTC, Anshnrag02 commented
sure sure


On Sat, 22 May 2021 at 22:16, Manjot Singh Sidhu ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Looks good, let me test it out.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/CircuitVerse/mobile-app/pull/96#pullrequestreview-666195957>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR44WTVHUUXCFO5OBHHKZJTTO7NU5ANCNFSM45KN2IQQ>
> .
>

2021-05-25 15:24 UTC, manjotsidhu approved these changes
LGTM, Works great on my device as well.

2021-05-25 15:25 UTC, merged